// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6VVX0lKE-ubHDNyVuutE80ND2mbcWqz0',
    appId: '1:144243140512:web:a556c13a3fb595592366c5',
    messagingSenderId: '144243140512',
    projectId: 'velo-5ae83',
    authDomain: 'velo-5ae83.firebaseapp.com',
    storageBucket: 'velo-5ae83.firebasestorage.app',
    measurementId: 'G-479G8EX014',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-SrXNRibNUlS9eZVbihFjx0bcdIMP06E',
    appId: '1:144243140512:android:c3286abeb2f279012366c5',
    messagingSenderId: '144243140512',
    projectId: 'velo-5ae83',
    storageBucket: 'velo-5ae83.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVbrzfL_Blh7jYd2-rjG7jNjYNEwjYHzQ',
    appId: '1:144243140512:ios:0c9bb41c6ac0a73f2366c5',
    messagingSenderId: '144243140512',
    projectId: 'velo-5ae83',
    storageBucket: 'velo-5ae83.firebasestorage.app',
    androidClientId: '144243140512-1nfaniet2viuu22i92fmq67c6t1ib1e1.apps.googleusercontent.com',
    iosClientId: '144243140512-d5675v0bu3jcd3u1km5jc2md06cjvo61.apps.googleusercontent.com',
    iosBundleId: 'com.example.velo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVbrzfL_Blh7jYd2-rjG7jNjYNEwjYHzQ',
    appId: '1:144243140512:ios:0c9bb41c6ac0a73f2366c5',
    messagingSenderId: '144243140512',
    projectId: 'velo-5ae83',
    storageBucket: 'velo-5ae83.firebasestorage.app',
    androidClientId: '144243140512-1nfaniet2viuu22i92fmq67c6t1ib1e1.apps.googleusercontent.com',
    iosClientId: '144243140512-d5675v0bu3jcd3u1km5jc2md06cjvo61.apps.googleusercontent.com',
    iosBundleId: 'com.example.velo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6VVX0lKE-ubHDNyVuutE80ND2mbcWqz0',
    appId: '1:144243140512:web:e78f2ebe51aa7d6b2366c5',
    messagingSenderId: '144243140512',
    projectId: 'velo-5ae83',
    authDomain: 'velo-5ae83.firebaseapp.com',
    storageBucket: 'velo-5ae83.firebasestorage.app',
    measurementId: 'G-BRJFZWCN0T',
  );
}
