name: velora
description: "An android application where you can plan, track, collaborate, inform and demonstrate on how to ride a bike and how to repair it manually with the use of Artificial Intelligence."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0" # Ensure that the SDK version is compatible with your current version

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.3.0
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  firebase_storage: ^12.4.2
  flutter_svg: ^2.0.17
  cloud_firestore: ^5.6.5
  delightful_toast: ^1.1.0
  curved_navigation_bar: ^1.0.6
  google_identity_services_web: ^0.3.3
  google_sign_in: ^6.2.2
  google_sign_in_android: ^6.1.35
  google_sign_in_ios: ^5.8.0
  google_sign_in_platform_interface: ^2.4.5
  google_sign_in_web: ^0.12.4+3
  email_validator: ^3.0.0
  table_calendar: ^3.2.0
  shared_preferences: ^2.5.2
  syncfusion_flutter_datepicker: ^28.2.9
  image_picker: ^1.1.2
  weather: ^3.1.1
  intl: ^0.20.2
  flutter_dotenv: ^5.1.0
  flutter_polyline_points: ^2.1.0
  google_maps_flutter: ^2.5.3
  location: ^8.0.0
  geolocator: ^13.0.2
  permission_handler: ^11.4.0
  google_places_flutter: ^2.1.0
  provider: ^6.1.2
  google_maps_flutter_platform_interface: ^2.11.1
  geocoding: ^3.0.0
  flutter_typeahead: ^4.8.0
  flutter_google_maps_webservices: ^1.1.1

  
dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/Icon.png" # Update this path with your logo's location
  adaptive_icon_foreground: "assets/images/Icon.png" # Optional for adaptive icons

flutter:
  uses-material-design: true

  assets:
    - assets/images/image1.png
    - assets/images/image2.png
    - assets/images/image3.png
    - assets/images/logo.png
    - assets/images/Google.png
    - assets/images/roadbike.png
    - assets/images/mountainbike.png
    - assets/images/fixie.png
    - assets/svg/add.svg
    - assets/svg/black-m.svg
    - assets/svg/black-w.svg
    - assets/svg/white-m.svg
    - assets/svg/white-w.svg
    - assets/images/rd-Handle.png
    - assets/images/rd-Frame.png
    - assets/images/rd-Saddle.png
    - assets/images/rd-Wheels.png
    - assets/images/rd-Shifter.png
    - assets/images/rd-Crank.png
    - assets/images/mb-Handle.png
    - assets/images/mb-Frame.png
    - assets/images/mb-Saddle.png
    - assets/images/mb-Wheels.png
    - assets/images/mb-Shifter.png
    - assets/images/mb-Crank.png
    - assets/images/fx-Handle.png
    - assets/images/fx-Frame.png
    - assets/images/fx-Saddle.png
    - assets/images/fx-Wheels.png
    - assets/images/fx-Break.png
    - assets/images/fx-Crank.png
    - assets/images/maps-location.png
    - assets/images/weather-background.png
    - assets/images/ai-bike.png




  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
